#
# Copyright 2017, Data61
# Commonwealth Scientific and Industrial Research Organisation (CSIRO)
# ABN 41 687 119 230.
#
# This software may be distributed and modified according to the terms of
# the BSD 2-Clause license. Note that NO WARRANTY is provided.
# See "LICENSE_BSD2.txt" for details.
#
# @TAG(DATA61_BSD)
#

components-$(CONFIG_APP_TESTS)        += sel4test-tests
sel4test-tests: common libsel4 libmuslc libcpio libsel4utils libsel4muslcsys libsel4allocman libsel4test libsel4testsupport libelf libplatsupport libsel4platsupport libsel4vspace libsel4simple-default libsel4debug libsel4sync
